# Generated by Django 4.1.3 on 2022-11-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0003_alter_networkobject_location_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkobject",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="electronics.networkobject",
            ),
        ),
    ]
