# Generated by Django 4.1.3 on 2022-11-08 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("electronics", "0004_alter_networkobject_supplier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="objectemployees",
            options={"verbose_name_plural": "Object Employees"},
        ),
        migrations.AlterModelOptions(
            name="presentproducts",
            options={"verbose_name_plural": "Present Products"},
        ),
        migrations.AlterField(
            model_name="objectemployees",
            name="employees",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="presentproducts",
            name="products",
            field=models.ManyToManyField(
                blank=True, null=True, to="electronics.product"
            ),
        ),
    ]
