# Generated by Django 4.1.3 on 2022-11-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0006_alter_objectemployees_employees_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                choices=[
                    ("television", "TV"),
                    ("phone", "Phone"),
                    ("tablet", "Tablet"),
                    ("notebook", "Notebook"),
                    ("headphones", "Headphones"),
                    ("camera", "Camera"),
                    ("refrigerator", "Refrigerator"),
                    ("printer", "Printer"),
                ],
                max_length=25,
            ),
        ),
    ]
