# Generated by Django 4.1.3 on 2022-11-09 08:13

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0007_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkobject",
            name="location_city",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="location_country",
                chained_model_field="country",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="electronics.city",
            ),
        ),
    ]
